CREATE TABLE room
(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(5) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE board
(
    id INT(10) NOT NULL,
    position VARCHAR(2) NOT NULL,
    piece VARCHAR(10) NOT NULL,
    CONSTRAINT board_PK PRIMARY KEY (id, position),
    FOREIGN KEY (id) REFERENCES room(id) ON DELETE CASCADE
);

CREATE TABLE player
(
    id INT(10) NOT NULL PRIMARY KEY,
    color VARCHAR (5) NOT NULL,
    FOREIGN KEY (id) REFERENCES room(id) ON DELETE CASCADE
);
